/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lawyer;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class ClientRegister extends javax.swing.JFrame {

    /**
     * Creates new form ClientRegister
     */
     String fileName = null;
    public ClientRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        notice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        pword = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        up = new java.awt.Button();
        submit = new javax.swing.JLabel();
        backing = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notice.setBackground(new java.awt.Color(255, 0, 51));
        notice.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(notice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 550, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 100, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Email Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Contact Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 160, 30));

        add.setBackground(new java.awt.Color(35, 35, 35));
        add.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(204, 204, 204));
        add.setBorder(null);
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 280, 30));

        email.setBackground(new java.awt.Color(35, 35, 35));
        email.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 280, 30));

        name.setBackground(new java.awt.Color(35, 35, 35));
        name.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setBorder(null);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 280, 30));

        pword.setBackground(new java.awt.Color(35, 35, 35));
        pword.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pword.setForeground(new java.awt.Color(204, 204, 204));
        pword.setBorder(null);
        jPanel1.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 280, 30));

        phone.setBackground(new java.awt.Color(35, 35, 35));
        phone.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(204, 204, 204));
        phone.setBorder(null);
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 280, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 300, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 300, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 300, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 290, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 300, 10));

        up.setActionCommand("upload");
        up.setBackground(new java.awt.Color(35, 35, 35));
        up.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        up.setForeground(new java.awt.Color(204, 204, 204));
        up.setLabel("Upload");
        up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upMouseClicked(evt);
            }
        });
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel1.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 130, 50));

        submit.setBackground(new java.awt.Color(35, 35, 35));
        submit.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        submit.setForeground(new java.awt.Color(204, 255, 255));
        submit.setText("SUBMIT");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 130, 50));

        backing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lawyer/back.png"))); // NOI18N
        backing.setText("ertgrs");
        backing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backingMouseClicked(evt);
            }
        });
        jPanel1.add(backing, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, 60));

        txt.setForeground(new java.awt.Color(35, 35, 35));
        txt.setText("jLabel8");
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 90, 20));

        pic.setBackground(new java.awt.Color(255, 255, 255));
        pic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 250, 230));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Present Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backingMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ClientLogin().setVisible(true);
    }//GEN-LAST:event_backingMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        String nam = name.getText();
        String pass = pword.getText();
        String mail = email.getText();
        String phn = phone.getText();
        String ad = add.getText();
        System.out.println(nam);
        //Code for getting the image into database
        String ima = txt.getText();
        String qsql = "insert into userRegistration(userName,phone,passwrd,email,addres,photo)values['"+nam+"','"+phn+"','"+pass+"','"+mail+"','"+ad+"','"+ima+"']";
        
        
        if (nam.isEmpty() || pass.isEmpty() || mail.isEmpty() || phn.isEmpty() || ad.isEmpty() || ima.isEmpty()) {

            notice.setText("Please fill up all fields");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager
                        .getConnection(
                                "jdbc:sqlserver://localhost:1433;databaseName=LawFirm;selectMethod=cursor", "sa", "123456");                
                String sq= "insert into userRegistration(userName,phone,passwrd,email,addres,photo)values('"+nam+"','"+phn+"','"+pass+"','"+mail+"','"+ad+"','"+ima+"')";
                
                sq = "select userName from userRegistration where userName = '"+nam+"'";
                PreparedStatement prepStmnt = null;
                ResultSet rs = null;
                prepStmnt = connection.prepareStatement(sq);
                rs = prepStmnt.executeQuery();      
                int limit = 0;
                while(rs.next()){
                    limit++;
                }
                if(limit > 0){
                    JOptionPane.showMessageDialog(null,"This userName is already registered");
                }
                else{
                
                String sql = "Insert into userRegistration"
                    +"(userName,phone,passwrd,email,addres,photo, sentRequest)"
                    +"values(?,?,?,?,?,?,?)";
                PreparedStatement pst = connection.prepareStatement(sql);
                pst.setString(1, nam);
                pst.setString(2, phn);
                pst.setString(3, pass);
                pst.setString(4, mail);
                pst.setString(5, ad);
                pst.setString(6, ima);
                pst.setInt(7, 0);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Registration Successful!!");
                name.setText("");
                pword.setText("");
                email.setText("");
                phone.setText("");
                add.setText("");
                pic.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_submitMouseClicked

    private void upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            fileName = f.getAbsolutePath();
            System.out.println(fileName);
            txt.setText(fileName);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_SMOOTH));
            pic.setIcon(imageIcon); 
    }//GEN-LAST:event_upMouseClicked
    }
    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JLabel backing;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField name;
    private javax.swing.JLabel notice;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField pword;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel txt;
    private java.awt.Button up;
    // End of variables declaration//GEN-END:variables
}
