/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lawyer;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class LawyerRegister extends javax.swing.JFrame {

    /**
     * Creates new form LawyerRegister
     */
    String fileName = null;
    public LawyerRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        notice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        pword = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        cer = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        pic = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nid = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txt2 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notice.setBackground(new java.awt.Color(255, 0, 51));
        notice.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(notice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 550, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Type");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 100, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Email Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Contact Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 160, 30));

        add.setBackground(new java.awt.Color(35, 35, 35));
        add.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(204, 204, 204));
        add.setBorder(null);
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 280, 30));

        email.setBackground(new java.awt.Color(35, 35, 35));
        email.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 280, 30));

        name.setBackground(new java.awt.Color(35, 35, 35));
        name.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setBorder(null);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 280, 30));

        pword.setBackground(new java.awt.Color(35, 35, 35));
        pword.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pword.setForeground(new java.awt.Color(204, 204, 204));
        pword.setBorder(null);
        jPanel1.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 280, 30));

        phone.setBackground(new java.awt.Color(35, 35, 35));
        phone.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(204, 204, 204));
        phone.setBorder(null);
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 280, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 300, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 300, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 290, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 290, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 290, 10));

        jLabel6.setBackground(new java.awt.Color(35, 35, 35));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("SUBMIT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 130, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lawyer/back.png"))); // NOI18N
        jLabel7.setText("ertgrs");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        txt.setForeground(new java.awt.Color(35, 35, 35));
        txt.setText("jLabel8");
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 90, 20));

        cer.setBackground(new java.awt.Color(255, 255, 255));
        cer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 300, 160));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("NID Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 140, 30));

        button1.setBackground(new java.awt.Color(35, 35, 35));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Upload Certificate Photo");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 140, 40));

        pic.setBackground(new java.awt.Color(255, 255, 255));
        pic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 180, 200));

        button2.setBackground(new java.awt.Color(35, 35, 35));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("Upload Profile Photo");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 150, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("User Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Office Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 140, 30));

        nid.setBackground(new java.awt.Color(35, 35, 35));
        nid.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nid.setForeground(new java.awt.Color(204, 204, 204));
        nid.setBorder(null);
        jPanel1.add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 280, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 300, 10));

        txt2.setForeground(new java.awt.Color(35, 35, 35));
        txt2.setText("jLabel8");
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 90, 20));

        combo.setBackground(new java.awt.Color(35, 45, 35));
        combo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        combo.setForeground(new java.awt.Color(204, 204, 204));
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criminal Law", "Civil Rights", "Digital Media and Internet", "Personal Injury", "Income Tax", "Entertainment" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 360, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        String nam = name.getText();
        String pass = pword.getText();
        String mail = email.getText();
        String phn = phone.getText();
        String ad = add.getText();
        String NID = nid.getText();
        String Type = (String)combo.getSelectedItem();
        System.out.println(nam);
        //Code for getting the image into database
        String ima = txt.getText();
         String ima2 = txt2.getText();
        String qsql = "insert into userRegistration(typ,lawyerName,lawyerPhone,officeAddress,passwrd"
                + ",email,NID,lawyerPhoto,certificatePhoto)values['"+Type+"','"+nam+"','"+phn
                +"','"+ad+"','"+pass+"','"+mail+"','"+NID+"','"+ima+"','"+ima2+"']";

        if (nam.isEmpty() || pass.isEmpty() || mail.isEmpty() || phn.isEmpty() || 
                ad.isEmpty() || ima.isEmpty()|| ima2.isEmpty()|| NID.isEmpty()|| Type.isEmpty()) {

            notice.setText("Please fill up all fields");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager
                .getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=LawFirm;selectMethod=cursor", "sa", "123456");
                String sq= "insert into lawyerRegistration(userName,phone,passwrd,email,addres,photo)values('"+nam+"','"+phn+"','"+pass+"','"+mail+"','"+ad+"','"+ima+"')";
                sq = "select lawyerName from lawyerRegistration where lawyerName = '"+nam+"'";
                PreparedStatement prepStmnt = null;
                ResultSet rs = null;
                prepStmnt = connection.prepareStatement(sq);
                rs = prepStmnt.executeQuery();      
                int limit = 0;
                while(rs.next()){
                    limit++;
                }
                if(limit > 0){
                    JOptionPane.showMessageDialog(null,"This userName is already registered");
                }
                else{
                String sql = "Insert into lawyerRegistration"
                +"(typ, lawyerName, rating, lawyerPhone, win, loss, totalCases, officeAddress, passwrd, email, NID, lawyerPhoto, certificatePhoto, limit)"
                +"values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement pst = connection.prepareStatement(sql);
                pst.setString(1, Type);
                pst.setString(2, nam);
                pst.setFloat(3, 0);
                pst.setString(4, phn);
                pst.setInt(5, 0);
                pst.setInt(6, 0);
                pst.setInt(7, 0);
                pst.setString(8, ad);
                pst.setString(9, pass);
                pst.setString(10, mail);
                pst.setString(11, NID);
                pst.setString(12, ima);
                pst.setString(13, ima2);
                pst.setInt(14, 0);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Registration Successful!!");
                name.setText("");
                pword.setText("");
                email.setText("");
                phone.setText("");
                add.setText("");
                cer.setText("");
                nid.setText("");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LawyerLogin().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            fileName = f.getAbsolutePath();
            System.out.println(fileName);
            txt.setText(fileName);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_SMOOTH));
            pic.setIcon(imageIcon); 
    }
    }//GEN-LAST:event_button2MouseClicked

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            fileName = f.getAbsolutePath();
            System.out.println(fileName);
            txt2.setText(fileName);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(cer.getWidth(), cer.getHeight(), Image.SCALE_SMOOTH));
            cer.setIcon(imageIcon); 
    }
    }//GEN-LAST:event_button1MouseClicked

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LawyerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LawyerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LawyerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LawyerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LawyerRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel cer;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nid;
    private javax.swing.JLabel notice;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField pword;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
