/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lawyer;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        String welClient = "D:\\Icon\\m.jpg";
        String welLaw = "D:\\Icon\\u.jpg";
        String l = "D:\\Icon\\logo.png";
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(welClient).getImage().getScaledInstance(wclient.getWidth(), wclient.getHeight(), Image.SCALE_SMOOTH));
        wclient.setIcon(imageIcon);
        imageIcon = new ImageIcon(new ImageIcon(welLaw).getImage().getScaledInstance(wlawyer.getWidth(), wlawyer.getHeight(), Image.SCALE_SMOOTH));
        wlawyer.setIcon(imageIcon);
        imageIcon = new ImageIcon(new ImageIcon(l).getImage().getScaledInstance(wlogo.getWidth(), wlogo.getHeight(), Image.SCALE_SMOOTH));
        wlogo.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wlawyer = new javax.swing.JLabel();
        wclient = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        wlogo = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wlawyer.setText("jLabel1");
        wlawyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wlawyerMouseClicked(evt);
            }
        });
        jPanel1.add(wlawyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 360, 280));

        wclient.setText("jLabel1");
        wclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wclientMouseClicked(evt);
            }
        });
        jPanel1.add(wclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 310, 280));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        jLabel3.setText("UKIL CHAI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 220, 110));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel4.setText("Lawyer");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 170, 50));

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel5.setText("Client");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 170, 50));

        wlogo.setText("jLabel1");
        jPanel1.add(wlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 80, 90));

        cross.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cross.setForeground(new java.awt.Color(255, 102, 102));
        cross.setText("X");
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossMouseClicked(evt);
            }
        });
        jPanel1.add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_crossMouseClicked

    private void wclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wclientMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ClientLogin().setVisible(true);
    }//GEN-LAST:event_wclientMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ClientLogin().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void wlawyerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wlawyerMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LawyerLogin().setVisible(true);
    }//GEN-LAST:event_wlawyerMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LawyerLogin().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cross;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel wclient;
    private javax.swing.JLabel wlawyer;
    private javax.swing.JLabel wlogo;
    // End of variables declaration//GEN-END:variables
}
